### ISSUE TITLE
Participant is not recognized

### ISSUE THREAD

**Issue by plehegar** [w3c/ash-nazg#206] opened 2021-06-17 20:07 UTC
The GitHub user is known to our W3C DB as a CSSWG participant and yet rejected by our repository manager.

https://labs.w3.org/repo-manager/pr/id/w3c/csswg-drafts/5763

https://www.w3.org/groups/wg/css/participants

@jonathantneal

**Comment by deniak** [comment] 2021-06-18 06:25
@jonathantneal the issue is now fixed.
It came from the fact that you currently own 2 W3C accounts (`jjonatha` and `jonneal`). The first account is the one participating in the different groups and also the one linked to your github account.
However, the repository manager was relying on your second account to check the IPR. I fixed the data and the PR can now pass the validation.
Your second account doesn't seem to be used so with your permission, I would like to close it.

**Comment by jonathantneal** [comment] 2021-06-18 06:55
Yes, please do. And thanks for getting me sorted out, @deniak! 🙏

**Closed** 2021-06-18 06:58 UTC
Labels: bug
