### ISSUE TITLE
IPR bot validating issue

### ISSUE THREAD

**Issue by Kieun** [w3c/ash-nazg#261] opened 2023-09-23 00:43 UTC
When I've created the PR for WebAuthn spec, the IPR does not properly get my membership for the group.

Here are the links:
- https://labs.w3.org/repo-manager/pr/id/w3c/webauthn/1972

I've submitted couple of PRs recently, and the IPR bot successfully verified my membership and IPR agreement info.

**Comment by deniak** [comment] 2023-09-25 05:13
@Kieun Thank you for the report. The issue is now fixed and your PRs have been validated.

**Closed by deniak** 2023-09-25 05:13 UTC

**Comment by Kieun** [comment] 2023-09-25 05:14
@deniak Thanks for the fix. :)
